### PR TITLE
Puffle Name check

### PR DESCRIPTION
**Pull request by AmusingThrone**
Adds a length and alphanumeric check.

### CODE REVIEW

**Comment by valid22** [comment]
```py
if not 4 < len(data.Name) < 26:
        return self.sendError(441)
```
More pythonic way

**Comment by AmusingThrone** [comment]
Sure, that works too. I'll update it accordingly.

**Comment by AmusingThrone** [comment]
I thought the puffle name was a minimum of 2 characters, and a max of 25?

**Comment by valid22** [comment]
For max of 25, no of characters should be less than 26. No minimum no of character is 4 (excluding spaces)

**Comment by AmusingThrone** [comment]
@valid22 Hopefully it's fine now?

**Comment by valid22** [comment]
Yep!

**Comment by AmusingThrone** [comment]
@TunnelBlanket I was thinking of adding a name check in here as well (swear words, links, etc), but also feel it would be better fit in its own plugin. Thoughts?

**Comment by ketnipz** [comment]
Good idea, it's probably worth checking names are **alphanumeric**. Checking for foul language is not something I'd be worried about right now. Maybe Houdini will have built in tools for stuff like that in the future but that's a long ways down the road.

Does anyone remember if pet names are allowed to even contain numbers? I don't remember. Might be worth making use of regex to ensure names are sensibly formatted?

**Comment by valid22** [comment]
@ketnipz Even if numbers are allowed, wouldn't it be ridiculous to call your pet with a number.

**Comment by AmusingThrone** [comment]
@ketnipz I left numbers in, just checking for alphanumeric.

**Comment by widd** [comment]
@valid22 
```
if not 26 > len(data.Name) > 4:
        return self.sendError(441)
```
No need to reverse everything - readability is important.

**Comment by valid22** [comment]
@widd Am used to do it in maths. LOL

**Pull request closed without merging**
